### ISSUE TITLE
Support for Yokozuna administration

### ISSUE THREAD

**Issue by peschkaj** [basho-labs/riak-dotnet-client#162]
See https://github.com/basho/yokozuna/issues/157

This should include:

- [ ] Create Schema
- [ ] Read Schema
- [ ] Creating an index
- [ ] Associating indexes with buckets
- [ ] listing an index

Not included is:

* Querying support - this should be provided by a SOLR provider

**Comment by lukebakken** [comment]
See #186 and #200
