### ISSUE TITLE
ServerValidationCallback (SSL Validation)

### ISSUE THREAD

**Issue by paigeadele** [basho-labs/riak-dotnet-client#220]
https://github.com/basho-labs/CorrugatedIron/search?utf8=%E2%9C%93&q=ServerValidationCallback

I'm guilty of doing this myself, but you should make the option to explicitly disable this available to the user

FWIW: https://github.com/search?q=ServerValidationCallback&type=Code&utf8=%E2%9C%93

**Comment by lukebakken** [comment]
Removed by 292f82c6c027ce4bbbbf7fcc1973ab7e9a170788

https://github.com/basho-labs/riak-dotnet-client/commit/292f82c6c027ce4bbbbf7fcc1973ab7e9a170788#diff-a1c095d5bab96b0061ad5cdcdd33217dL101
