### ISSUE TITLE
Improvements to RiakResult classes to allow for stubbing of results from riak

### ISSUE THREAD

**Issue by vikmn** [basho-labs/riak-dotnet-client#264]
I am currently starting on the journey to using Riak with one of my .net projects within my organisation and have started using this nuget package. What i am looking to do is write various behaviours depending on the RiakResultStatus code embeeded within the RiaKresult object which does mean i am looking out use mocked/stubbed versions of the RiakResult<T> and/ Riakresult class. Unfortunately both these classes have either their protected/private or made internal methods which make it hard to create stubs for these. Is there an approach or class i could use to return stubbed instances of these classes or maybe could these be made to inherit from an IRiakResult ior IriakResult<T> interface for instance to allow the stubbing and mocking of these responses?

**Comment by lukebakken** [comment]
Hi @vikmn could you please give some example code showing where you're blocked writing your tests? Which mocking library are you using?

**Comment by vikmn** [comment]
I am using Rhino Mocks as my mocking library. a simple example would be 
StubOf<IRiakClient>().Stub(x => x.Batch(Arg<Func<IRiakBatchClient, IEnumerable<RiakResult<RiakObject>>>>.Is.Anything)).Return(new[] {new RiakResult<RiakObject>() );
When i do this i get an error suggesting that the private constructor cannot be accessed.

**Comment by vikmn** [comment]
if you look at the RiakResult class this has a constructor that is protected and if you also look at the other class  RiakResult<TResult> it has a private constructor. This prevents the class from being stubbed out.

**Comment by lukebakken** [comment]
Thanks for the details. Which version of the client are you using?

**Comment by vikmn** [comment]
I am currently using the version from the corrugated iron nugget package
which is where I picked up the issue but having looked at the new
repository which seems a port of the corrugated iron repo still notice the
same

**Comment by lukebakken** [comment]
Yes, we have not changed these classes yet. Let me work on this this morning and I'll let you know when a new beta release is available. You will want to choose "include prerelease" in the NuGet package manager dropdown, after which you can search for the `RiakClient` library.

**Comment by lukebakken** [comment]
Hi @vikmn -

Please see the current beta release with changes to address this issue:

https://github.com/basho-labs/riak-dotnet-client/releases/tag/v2.0.0-beta5
https://www.nuget.org/packages/RiakClient/

Thank you for reporting this.
