### ISSUE TITLE
In-Memory Back-end

### ISSUE THREAD

**Issue by Iristyle** [basho-labs/riak-dotnet-client#53]
Background

* Using CorrugatedIron / Riak 1.2 on a new project.
* Developing on Windows, with local Ubuntu VMs hosting Riak
* Using pretty standard fare repository interfaces along with dependency injection.
* As we go, we've ended up writing a number of in-memory variants of these repo interfaces to speed up unit tests, provide simulated data, etc, etc.  Basically for any situation where we're testing something business-y and not persistence-y.

But I'm starting to think that there's a lot of ceremony that goes along with building these in-memory repos, and that it would be nice to push this responsibility off to CorrugatedIron.

Since the Riak datamodel is so simple, it can be pretty closely simulated with a `ConcurrentDictionary<string, object>`.

I haven't looked too closely at your code in a while, but I think that this would involve

* Implementing some new classes on top of the standard client interfaces
* Providing a config switch that denotes you're running on a fake Riak.
* Some combination of the two

I think the RavenDB client has a feature like that if I recall correctly.

Thoughts?

**Comment by alexmoore** [comment]
Hi @Iristyle, did you ever make any progress on this?  We're in the process of cleaning out old issues.

Thanks!

**Comment by Iristyle** [comment]
Unfortunately I'm not able to use Riak / ElasticSearch on a daily basis anymore (haven't been for nearly 2 years now).

**Comment by lukebakken** [comment]
Thanks you for the update. At this point we'll close the request but may revisit the idea in the future.
